-- ==============================================================================
-- MIGRATION SCRIPT: NEWS INFRASTRUCTURE
-- Run this in your Supabase SQL Editor.
-- This script is strictly additive and safe to run on production.
-- It does NOT modify existing tables like profiles, messages, rooms, etc.
-- ==============================================================================

-- ==============================================================================
-- 1. NEWS TABLE (Admin-only insert, Public read)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT UNIQUE NOT NULL,
    category TEXT,
    sentiment TEXT,
    importance INTEGER CHECK (importance BETWEEN 1 AND 10),
    market_impact TEXT,
    assets JSONB DEFAULT '[]'::jsonb,
    directions JSONB DEFAULT '{}'::jsonb,
    confidence INTEGER CHECK (confidence BETWEEN 0 AND 100),
    time_horizon TEXT,
    analysis TEXT,
    source TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    image_url TEXT,
    structured_analysis JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safely add structured_analysis column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'news' AND column_name = 'structured_analysis'
    ) THEN
        ALTER TABLE public.news ADD COLUMN structured_analysis JSONB DEFAULT '{}'::jsonb;
    END IF;
END $$;


ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'News are viewable by everyone' AND tablename = 'news'
    ) THEN
        CREATE POLICY "News are viewable by everyone" 
        ON public.news FOR SELECT 
        USING ( true );
    END IF;
END $$;

-- Insert/Update restricted to Service Role Key (backend only), so no RLS policies needed for them.

-- Auto-update updated_at trigger for news table
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'update_news_modtime' AND tgrelid = 'public.news'::regclass
    ) THEN
        CREATE TRIGGER update_news_modtime
        BEFORE UPDATE ON public.news
        FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
    END IF;
END $$;


-- ==============================================================================
-- 2. REFRESH LOGS TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.refresh_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_seconds NUMERIC,
    inserted_count INTEGER DEFAULT 0,
    duplicate_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.refresh_logs ENABLE ROW LEVEL SECURITY;

-- Service Role only table, no public RLS needed


-- ==============================================================================
-- 3. REFRESH LOCK TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.refresh_locks (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    is_locked BOOLEAN DEFAULT false,
    locked_at TIMESTAMP WITH TIME ZONE,
    locked_by TEXT
);

INSERT INTO public.refresh_locks (id, is_locked) 
VALUES (1, false) 
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.refresh_locks ENABLE ROW LEVEL SECURITY;

-- Service Role only table, no public RLS needed


-- ==============================================================================
-- 4. CHAT MESSAGES TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_slug TEXT NOT NULL DEFAULT 'global',
    username TEXT NOT NULL,
    display_name TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Chat messages are viewable by everyone' AND tablename = 'chat_messages'
    ) THEN
        CREATE POLICY "Chat messages are viewable by everyone" 
        ON public.chat_messages FOR SELECT 
        USING ( true );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can insert chat messages' AND tablename = 'chat_messages'
    ) THEN
        CREATE POLICY "Anyone can insert chat messages" 
        ON public.chat_messages FOR INSERT 
        WITH CHECK ( true );
    END IF;
END $$;


-- ==============================================================================
-- 5. INDEXES FOR PERFORMANCE
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_news_created_at ON public.news(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_category ON public.news(category);
CREATE INDEX IF NOT EXISTS idx_chat_room ON public.chat_messages(room_slug);
CREATE INDEX IF NOT EXISTS idx_chat_created ON public.chat_messages(created_at DESC);
