-- ==============================================================================
-- TRADE TRENDS: SUPABASE RLS POLICIES
-- Execute this script in your Supabase SQL Editor.
-- ==============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- PROFILES TABLE POLICIES
-- ==============================================================================

-- 1. Anyone can read profiles (Public Read)
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.profiles FOR SELECT 
USING ( true );

-- 2. Users can only insert their own profile
CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT 
WITH CHECK ( auth.uid() = id );

-- 3. Users can only update their own profile
CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING ( auth.uid() = id )
WITH CHECK ( auth.uid() = id );

-- ==============================================================================
-- MESSAGES TABLE POLICIES
-- ==============================================================================

-- 1. Anyone can read chat messages (Public Read)
CREATE POLICY "Messages are viewable by everyone" 
ON public.messages FOR SELECT 
USING ( true );

-- 2. Authenticated users can only insert messages belonging to themselves
CREATE POLICY "Authenticated users can insert their own messages" 
ON public.messages FOR INSERT 
TO authenticated 
WITH CHECK ( auth.uid() = user_id );

-- Note: No UPDATE or DELETE policies are provided for messages. 
-- This ensures the chat log is append-only and cannot be altered.

-- ==============================================================================
-- ROOMS TABLE POLICIES (GAME ARENA)
-- ==============================================================================

-- WARNING: The game logic uses anonymous client-side UUIDs for players. 
-- To allow the game to function without requiring users to log in, 
-- these policies must be fully public.

-- 1. Rooms are viewable by everyone (Public Read)
CREATE POLICY "Rooms are viewable by everyone" 
ON public.rooms FOR SELECT 
USING ( true );

-- 2. Anyone can create a room (Public Insert)
CREATE POLICY "Anyone can create a room" 
ON public.rooms FOR INSERT 
WITH CHECK ( true );

-- 3. Anyone can update a room (Public Update)
CREATE POLICY "Anyone can update a room" 
ON public.rooms FOR UPDATE 
USING ( true )
WITH CHECK ( true );

-- 4. Anyone can delete a room (Public Delete - Needed for disbanding rooms)
CREATE POLICY "Anyone can delete a room" 
ON public.rooms FOR DELETE 
USING ( true );

-- ==============================================================================
-- NEWS TABLE (Admin-only insert, Public read)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    link TEXT UNIQUE NOT NULL,
    category TEXT,
    sentiment TEXT,
    importance INTEGER CHECK (importance BETWEEN 1 AND 10),
    market_impact TEXT,
    assets JSONB DEFAULT '[]'::jsonb,
    directions JSONB DEFAULT '{}'::jsonb,
    confidence INTEGER CHECK (confidence BETWEEN 0 AND 100),
    time_horizon TEXT,
    analysis TEXT,
    source TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "News are viewable by everyone" 
ON public.news FOR SELECT 
USING ( true );

-- Insert/Update restricted to Service Role Key (backend only), so no RLS policies needed for them.

-- Auto-update updated_at trigger
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_news_modtime
BEFORE UPDATE ON public.news
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- ==============================================================================
-- REFRESH LOGS TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.refresh_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_seconds NUMERIC,
    inserted_count INTEGER DEFAULT 0,
    duplicate_count INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.refresh_logs ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- REFRESH LOCK TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.refresh_locks (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    is_locked BOOLEAN DEFAULT false,
    locked_at TIMESTAMP WITH TIME ZONE,
    locked_by TEXT
);

INSERT INTO public.refresh_locks (id, is_locked) VALUES (1, false) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.refresh_locks ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- CHAT MESSAGES TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_slug TEXT NOT NULL DEFAULT 'global',
    username TEXT NOT NULL,
    display_name TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Chat messages are viewable by everyone" 
ON public.chat_messages FOR SELECT 
USING ( true );

CREATE POLICY "Anyone can insert chat messages" 
ON public.chat_messages FOR INSERT 
WITH CHECK ( true );

-- ==============================================================================
-- INDEXES FOR PERFORMANCE
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_news_created_at ON public.news(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_category ON public.news(category);
CREATE INDEX IF NOT EXISTS idx_chat_room ON public.chat_messages(room_slug);
CREATE INDEX IF NOT EXISTS idx_chat_created ON public.chat_messages(created_at DESC);
